### ISSUE TITLE
Link between Secret ID and Miele Account fails

### ISSUE THREAD

**Issue by xziBBerx** [HomeAssistant-Mods/home-assistant-miele-OLD-FORK-DO-NOT-USE#11]
Hello,

if i try to link my secretID/secretToken to my Miele Account i get following error:

`Something went wrong when attempting authenticating with Miele@home. The error encountered was (missing_token) Missing access token parameter.. Please try again!`

I run pip3 install requests_oauthlib in my Docker container via shell -> Requirement already satisfied

How i can fix this and link my account?

**Comment by AndersTao** [comment]
@xziBBerx I also get this error when I upgrade HA
Removing the `.miele-token-cache` file, restart, and sign back into Miele again solved it.

It is not a fix but works for now 🤷🏼‍♂️

**Comment by xziBBerx** [comment]
@AndersTao Unfortunately it didn't work for me. I've just started the application.
