### ISSUE TITLE
Unable to link Miele@mobile account with API token

### ISSUE THREAD

**Issue by albatorsk** [HomeAssistant-Mods/home-assistant-miele-OLD-FORK-DO-NOT-USE#13]
Linking my Miele@mobile account has previously worked just fine, but when I tried to do so about a week ago it no longer works.

I get an error in German that roughly translates to "Account linking failed."

![miele-failed-account-linking](https://user-images.githubusercontent.com/16045270/99846621-fd419100-2b76-11eb-8598-24e849ae4189.jpg)

The Miele@mobile app works fin using the same credentials, and I can see and control my washing machine in the app.

I'm running Home Assistant 0.118.1 on a supervised install.

**Comment by kloknibor** [comment]
Hmm I need to refresh my own token right now, I'll see what happens

**Comment by kloknibor** [comment]
Please request your client_id and secret here : https://www.miele.com/f/com/en/register_api.aspx these are not your normal miele login credentials.
