### ISSUE TITLE
HA 0.111.0: Warning - deprecated `base_url`

### ISSUE THREAD

**Issue by mamoel666** [HomeAssistant-Mods/home-assistant-miele-OLD-FORK-DO-NOT-USE#3]
I just updated to HA 0.111.0 and now I see this warning in the log:

    WARNING (MainThread) [homeassistant.components.http] Detected use of deprecated `base_url` 
    property, use `homeassistant.helpers.network.get_url` method instead. Please report issue to the 
    custom component author for miele using this method at custom_components/miele/__init__.py, 
    line 107: callback_url = '{}{}'.format(hass.config.api.base_url, AUTH_CALLBACK_PATH)

    /config/custom_components/miele/miele_at_home.py:106: RuntimeWarning: coroutine 
    'MieleOAuth.refresh_token' was never awaited

      self.refresh_token()

    RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by kloknibor** [comment]
Fixed with 3848ce2d34a9e8093ac56d211ee001c7a08df197 please update
