### ISSUE TITLE
TypeError: 'coroutine' object is not iterable

### ISSUE THREAD

**Issue by vistalba** [HomeAssistant-Mods/home-assistant-miele-OLD-FORK-DO-NOT-USE#5]
For me this integration isn't working anymore since a few weeks.
I run in this error. I already reinstalled, deleted the hidden token file and reconfigured and also created a new client_secret at Miele Developer site.
Noting helped. I alway get this error after start of HA and all entities are unavailable:

```
Protokolldetails ( ERROR )
Logger: homeassistant.setup
Source: custom_components/miele/miele_at_home.py:46
First occurred: 13:28:22 (1 occurrences)
Last logged: 13:28:22

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 191, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 127, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 46, in get_devices
    for home_device in home_devices:
TypeError: 'coroutine' object is not iterable
```

`configuration.yaml`:
```
...
miele:
    client_id: !secret miele_clientid
    client_secret: !secret miele_clientsecret
    lang: de
    cache_path: /config/.storage/miele
...
```

`secrets.yaml`:
```
...
miele_clientid: 1234567-abcd-acdb-1234-123456adcb2
miele_clientsecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
...
```

`Version Infos`:
```
Home Assistant 0.114.3 @ESX VM
Supervisor Version: 235
System: HassOS 4.12 (production)
```

Any idea how I can solve this issue?

**Comment by swifty99** [comment]
same here

**Comment by kloknibor** [comment]
Could you try it without the !secret just to sure if works there. Somebody else mentioned they had problems with this

**Comment by kloknibor** [comment]
Because of a recent change in the structure of the git repo this repo has been renamed and will be no longer active. When you still require support with your question/issue please open a new issue at : https://github.com/HomeAssistant-Mods/home-assistant-miele
