### ISSUE TITLE
Wrong programType

### ISSUE THREAD

**Issue by CineMAC-HA** [HomeAssistant-Mods/home-assistant-miele-OLD-FORK-DO-NOT-USE#8]
Hi! :slight_smile:
at first, many thanks for this Great Integration!
I have a problem with the sensor programType. This habe always the state „eigenes Programm“. What is wrong in my config? The other sensors all Fine.

Thanks and regards
Frank

**Comment by kloknibor** [comment]
I'm not sure what you mean with this issue. Anyway you can provide more information?

**Comment by CineMAC-HA** [comment]
Hi, thanks for your response. All is fine! 

https://community.home-assistant.io/t/miele-home-miele-mobile-component/64508/211
